on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <preview|production>"
        required: true
        default: "preview"
jobs:
  deploy:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./site
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: npm install && npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            case "${{ github.event.inputs.environment }}" in
              "production")
                pages deploy ./out --project-name=pikatorrent-site
                ;;
              "preview")
                pages deploy ./out --project-name=pikatorrent-site --branch=preview
                ;;
            esac
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
